# Generated by Django 4.1.7 on 2023-03-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='passord',
            new_name='password',
        ),
    ]
